version: '3.8'

services:
  trading-alert-system:
    build: .
    container_name: trading_alert_system
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.path.append('/app'); from src.config.settings import settings; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
